### ISSUE TITLE
Read from Gist Broken (Presets)

### ISSUE THREAD

**Issue by bwestergard** [tmcw/projectityourself#12]
Reading from a gist seems to be broken. Clicking any of the links gives "undefined" in both textareas. When I click one of the links the load handler attempts to read from d.files['x.js'] and d.files['y.js'], but d.files only contains one file for all of the existing presets, each containing two full function definitions (Project It Yourself seems to wrap entered code in function blocks itself as of 0231eb4811bed2b6a119770b38eb049f3c457bf7).

The convention Project It Yourself expects is pretty clear, so [this reformatting](http://macwright.org/projectityourself/#7051505) works.

Cool tool, by the way.

**Comment by tmcw** [comment]
Yep, this is going to just get a clean rewrite - learned a lot since this was implemented.
