### ISSUE TITLE
Re-clicking a preset after editing does not reload original preset

### ISSUE THREAD

**Issue by vlandham** [tmcw/projectityourself#5]
Very interesting project.

Noticed a small issue that might be worth fixing.

To reproduce:
- select preset (like Sinusoidal)
- make a modification to x or y function
- the preview map should change reflecting your change
- re-click the same preset (Sinusoidal)

Expected:
The original Sinusoidal projection is reloaded into the preview and x / y functions

Actual:
Modified version stays loaded
(probably due to the fact that currently the id in the url doesn't change from the default's id once a modification has occurred to the preset).

Thanks!

**Comment by tmcw** [comment]
Good catch! Will look at ways to fix this...

**Comment by tmcw** [comment]
Bare-bones redesign removes concept of presets http://www.macwright.org/projectityourself/
