### ISSUE TITLE
Clicking a preset should load preset before rendering

### ISSUE THREAD

**Issue by llimllib** [tmcw/projectityourself#7]
Also, if the rendering mode is stateful, there should be some indication of what is the present state of the software.

Steps to surprise:
1. Render some projection in super-hifi. Get an awesome map! Awesome! (Not sarcasm, the new super hi-fi mode is sweet)
2. Click some other projection
3. wait
4. wait
5. wait (still no info about the projection displayed in the x = or y = boxes)
6. finally, the super-hifi image renders, and the function is displayed in the x= and y= boxes.
7. Realize that the software made a super hi-fi map before displaying the projection to you, feel kinda dumb

I think you should display the projection functions in the x= and y= boxes, and setTimeout the rendering function so that I can read them while I wait. Add some indication of what the current mode is.

I'd be happy to implement this if you agree.

**Comment by tmcw** [comment]
True, true. The rendering mode currently is a sort of blend of statefulness and not. Clarifying this would be definitely good, so give it a shot if there's some way to make it more straightforward.

**Comment by llimllib** [comment]
Is the server code somewhere?

**Comment by tmcw** [comment]
There is none - the site runs on gh-pages and is html + js.

**Comment by llimllib** [comment]
hmmm... I was confused by the script reference to 127.0.0.1:1337 , but that doesn't work on http://macwright.org/projectityourself/ either. My bad

**Comment by tmcw** [comment]
Ah, I'll remove that. It's for https://gist.github.com/2394031

**Comment by tmcw** [comment]
Bare-bones redesign removes concept of presets http://www.macwright.org/projectityourself/
