### ISSUE TITLE
feature request: indicatracies

### ISSUE THREAD

**Issue by sumguysr** [tmcw/projectityourself#8]
It'd be cool if projectityourself could overlay Tissot or Goldberg-Gott indicatrices on the renderings.

http://en.wikipedia.org/wiki/Tissot%27s_indicatrix
http://arxiv.org/abs/astro-ph/0608501

**Comment by tmcw** [comment]
Totally, good idea and it'll be a lot more possible with a d3js port I'm planning to do.

**Comment by tmcw** [comment]
Happy to accept a PR implementing this feature, but I don't want to indicate that I'm working on it currently, so closing this issue!
